[project]
authors = ["Hoog-V <hogeweyv@gmail.com>"]
name = "database-builder"
channels = ["https://fast.prefix.dev/conda-forge", "https://repo.prefix.dev/pypdfium2-public", "https://repo.prefix.dev/pytorch"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[dependencies]
pip = "*"
python = "3.12.*"
python-dotenv = "*"
linkify-it-py = "*"
loguru-mypy = "*"
nbconvert = "*"
pandas-stubs = "*"
pydantic = "*"
pytest-profiling = "*"
pytest-xdist = "*"
pytest = "*"
ruff = "*"
ssort = "*"
tinycss2 = "*"
types-openpyxl = "*"
types-requests ="*"
compilers = "*"
pkg-config = "*"
rattler-build = "*"
black = "*"
cibuildwheel = "*"
creosote = "*"
debugpy = "*"
isort = "*"
lefthook = "*"
anyio = "*"
fastapi = "*"
openai = "*"
qdrant-client = "*"
pyarrow = "*"


[activation.env]
PYTHONNOUSERSITE = "1"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH" 


[pypi-dependencies]
scikit-learn = "*"
sentence-transformers = "*"
spacy = "*"
torch = "*"
docling = "*"
lingua-language-detector = "*"
typedb-driver = "==2.29.2"
span-marker = "*"
langfuse = "*"
unidecode = "*"
asapi = "*"
azure-identity = "*"
microsoft-kiota-authentication-azure = "*"
msgraph-sdk = "*"
pathvalidate = "*"
lychee = "*"
mypy = "*"

[target.linux-64.dependencies]
python-devtools = "*"         # Optional but useful
#cuda-toolkit = "12.9.0.*" # For use with cuda

[target.linux-64.tasks]
vscode = 'env -u LD_LIBRARY_PATH code .'

[target.osx.tasks]
vscode = 'env -u LD_LIBRARY_PATH code .'

[target.osx-arm64.tasks]
vscode = 'env -u LD_LIBRARY_PATH code .'

[tasks]
lint = "ruff check"
typecheck = "mypy ."
test = "pytest -q"
lefthook-ci = "lefthook run ci"